### PR TITLE
Add R support

### PR DESCRIPTION
**Pull request by BirgerK**
See more in #15

### CODE REVIEW

**Comment by dylanmei** [comment]
I will fire this up shortly. Will you also remove this line from your PR? It removes Zeppelin's `SparkR` notebook/tutorial which I think we'd like to make available along with these changes.

https://github.com/dylanmei/docker-zeppelin/blob/master/Dockerfile#L53

**Comment by dylanmei** [comment]
My first attempt to build this failed.

```
[ERROR] Could not find the selected project in the reactor: r @ 
Could not find the selected project in the reactor: r -> [Help 1]
```

I notice there is no "r" module in Zeppelin's top-level pom.xml. There are however `-Pr` and `-Psparkr`, which is confusing. It seems like the direction they are going with R support is not fully worked out.

**Comment by BirgerK** [comment]
I will remove the line, yes.

And that's confusing. But how about just using their maven-profiles? I guess they include everything Zeppelin needs. Maybe this image is even missing something wie don't know?

Die you compare the image-size by using maven-profiles and your way?

**Comment by dylanmei** [comment]
Using the `-Pr` profile brings the image from 1.69Gb to 2.47Gb. But just adding `-Pr` didn't make the `%r` interpreter available to me yet.

**Comment by BirgerK** [comment]
The `%r`-interpreter is "hidden" in the `spark`-interpreter. Beneath to `spark` you see a list of %-entries. On my installation `%r` appears there.

**Comment by dylanmei** [comment]
I must be missing something. :confused: 

I needed to add `-Pr` to get it to even build. But now that it's built I don't see the hidden `%r` interpreter in the `spark`-interpreter. 

zeppeline-spark-r

**Comment by BirgerK** [comment]
Seems like they're doing something in the maven-profiles.

**Pull request closed without merging**
